// Generate a random skill name
function generateSkillName() {
    const firstPart = [
        "Maestro", "Magus", "Occultist", "Sorcerer", "Warlock","Necromancer", "wizard", "Spirit", "Hellhound", "Fiend", "Demon", "Impish", "Sinful", "Ruthless", "Evil", "Netherworld", "Merciless", "Colossal", "Monstrous", "Brutal","Cruel", "Inhumane","Berserk", "Immortal","Dark", "Shadow", "Poison", "Death", "Darkness", "Void", "Demonic", 
        "Cursed", "Blood", "Inferno", "Undead", "Dead", "Abyss", "Abyssal", "Soul", "Blight", "Nightmare", "Night", "Moonlight",
        "Infernal", "Hell", "Hellish", "Grim", "Eternal", "Vile", "Malice", 
        "Wicked", "Necrotic", "Corrupt", "Searing", "Feral", "Unholy", "Phantom",
        "Malevolent", "Sinister", "Diabolic", "Gore", "Ruinous", "Tormented", "Fiendish",
        "Desolate", "Forsaken", "Accursed", "Devilish", "Blackened", "Ravaged",
        "Lurking", "Tainted", "Oblivion", "Profane", "Venomous", "Chaotic", 
        "Shattered", "Tragic", "Calamitous", "Cataclysmic", "Dire", "Twisted", "Unlit", "Ominous", "Morbid", "Spectral",
        "Decayed", "Atomic", "Vicious","Dreadful", "Ghastly", "Hateful", "Spiteful", "Acheron", "Damned", "Corrupted",
        "Malevolent", "Maledict", "Dread", "Gloom", "Despair", "Frenzied", "Harbinger", "Vampiric", "Vengeful", "Celestial", "Disturbing", "Haunted", "Lich", "Mind", "Aura of ", "Auspicious", "Elemental", "Ether", "Ghostly", "Guilt", "Soulless", "Cultist", "Divine", "Unyielding", "Relic", "Machiavellian", "Unfortunate", "Wretched", "Deep", "Eldritch", "Emptiness", "Baneful", "Ancient", "Acid", "Insane", "Unkind", "Mean", "Dominant", "Supreme", "Powerful", "Superior", "Outrageous", "Super", "Explosive", "Obscure", "Shrouded", "Psychic", "Astral", "Otherworldly", "Paranormal", "Prophet", "Telekinesis", "Blasphemous", "Ethereal", "Stellar", "Reality", "Galactic", "Astronomical", "Nightfall", "Menacing", "Terrifying", "Midnight", "Eclipse", "Nocturnal", "Ravenous", "Mythic", "Arcane", "Runic", "Echanted", "Fractured", "Anarchic", "Pandemonic", "Unfettered", "Wild", "Unleashed", "Nebulous", "Cosmic", "Singular", "Quantum", "Antimatter", "Seismic", "Dual", "Triple", "Centuple", "Manifold", "Relentless", "Thousands", "Million", "Billion", "Infinite", "Limitless", "fathomless", "Godly", "Boundless", "Virtual", "Painful", "Titan", "Mighty", "Bone", "Skull", "Killing", "Iron", "Judas", "Brazen", "Scavenger", "Heretic", "Beast", "Armageddon", "Mortal", "Apocalyptic", "Reaper", "Unreal", "Chaos", "Corpse", "Crypt", "Dusk", "Fallen", "Digital", "Singularity", "Nuclear", "Fractal", "Ghost", "Cortex", "Temporal", "Chronos", "Trickster", "Juggernaut", "Hades", "Medusa", "Apophis", "Entropy", "Inexorable", "Unstoppable", "Immutable", "Endless", "Perpetual", "Unquenchable", "Unshakable", "Indestructible", "Unbreakable", "Burial", "Fatal", "Dimentional", "Ice", "Toxic", "Condemning", "Almighty", "All-powerful", "Omnipotent", "Gigantic", "Unfathomable", "Preeminent", "Great", "Imposing", "Inscrutable", "Immeasurable", "Inflicting"
    ];
    const secondPart = [
        "Punch", "Bolt", "Blast", "Beam", "Laser", "Bullet", "Wave", "Pulse", "Cannon", 
        "Orb", "Dart", "Surge", "Jet", "Arrow", "Spear", "Bomb", "Strike", "Consequence", "Outcome", "Effect",
        "Bind","Grasp", "Superheat", "Rush", "Flash",
        "Burst", "Cloak", "Fang", "Vortex", "Storm", "Howl", "Touch", "Flare", "Fist",
        "Corrosion", "Decay", "Shred", "Pierce", "Eruption", "Pain", "Ruin", "Slash",
        "Scourge", "Implosion", "Detonation", "Crush", "Venom", "Crack", "Splinter",
        "Meltdown", "Sear", "Vapor", "Fracture", "Release", "Annihilation", "Scald",
        "Smash", "Injection", "Tear", "Dissolution", "Quake", "Fragment", "Collapse",
        "Disintegrate", "Atomizer", "Evaporate", "Breakdown", "Engulf", "Devastation", "Assault", "Maelstrom", "Bender", "Flux", "Power", "Leech", "Lock", "Spike", "Burden", "Disruption", "Fear", "Echo", "Agony", "Suffering", "Torment", "Affliction", "Blaze", "Incantation", "Renewal", "Haste", "Immolation", "Sacrifice", "Subversion", "Shame", "Form", "Thorns", "Equinox", "Mist", "Flesh", "Silence", "Vow", "Possession", "Atrocity", "Misery", "Sorrow", "Abomination", "Trap", "Explosion", "Boom", "Thunder", "Fire", "Fireball", "Hex", "Flame", "Rain", "Punishment", "Purgatory", "Tribulation", "Trauma", "Entombment", "Breath", "Sinestra", "Voodoo", "Skinning", "Malediction", "Eye", "Swamp", "Descend", "Ruling", "Invocation", "Summoning", "Torrent", "Nova", "Whirlwind", "Chant", "Manifestation", "Barrage", "Charge", "Leach", "Tempest", "Cyclone", "Typhoon", "Hurricane", "Tornado", "Terrors", "Trial", "Being", "Mana", "Saw", "Blade", "Bleed", "Absorption", "Assimilation", "Intimidation", "Javelin", "Harpoon", "Spire", "Dagger", "Whip", "Cataclysm", "Combustion", "Ray", "Arc", "Current", "Discruption", "Seal", "Clash", "Ram", "Spite", "Wraith", "Claw", "Gaze", "Stare", "Pressure", "Influence", "Impact", "Authority", "World", "Corruption", "Manipulation", "Control", "Puppeteering", "Hypnosis", "Chains", "Dissection", "Ritual", "Plasma", "Rage", "Madness", "Energy", "Domination", "Transformation", "Rampage", "Bloodlust", "Frenzy", "Onslaught", "Carnage", "Grip", "Fury", "Breaker", "Intent", "Apocalypse", "Destruction", "Maiden", "Guillotine", "Pillory", "Cage", "Crusher", "Ripper", "Spider", "Snake", "Magic", "Spell", "Damage", "Stabbing", "Cut", "Wound", "Injury", "Bayonet", "Chop", "Chock", "knives", "Fate", "Wrath", "Requiem", "Fall", "Descent", "Plague", "Blight", "Havoc", "End", "Assassination", "Defeat", "Beating", "Bang", "Hammer", "Play", "stiletto", "Swords", "Light", "Pendulum", "Device", "Time", "Hour", "Existence", "Survival", "Scythe", "Suffocation", "Anomaly", "Aberration", "Disorder", "Order", "Command", "Grave", "Requital", "Arcana", "Embrace", "Error", "Bug", "Glitch", "Exploit", "System", "Overdrive", "Corruptor", "Distortion", "Nemesis", "Disruptor", "Overload", "Rift", "Stasis", "manipulator", "Unraveling", "Cascade", "Nexus", "Dissolution", "Disintegration", "Epoch", "Crumbling", "March", "Obelisk", "Sentinel", "Leviathan", "Monolith", "Pillar", "Bastion", "Masquerade", "Ground", "Shake", "Shiver", "Rockets", "Sanction", "Bazooka", "Sanctification", "Banishment", "Bite", "Baptism", "Blasphemy", "Sacrilege", "Crucifixion", "Fatality", "Accident", "Empalement", "Reckoning", "Judgment", "Damnation", "Unravel", "Legacy", ""
    ];

    return firstPart[Math.floor(Math.random() * firstPart.length)] + " " + secondPart[Math.floor(Math.random() * secondPart.length)];
}

const opponents = [
    "Regular Human",
    "Villager",
    "Angry Farmer",
    "Militia Recruit",
    "Town Guard",
    "Peasant Warrior",
    "Village Guard",
    "Bandit",
    "Thief",
    "Mercenary",
    "Foot Soldier",
    "Soldier",
    "Elite Soldier",
    "Crossbowman",
    "Spearman",
    "Swordsman",
    "Archer",
    "Hunter",
    "Beast Tamer",
    "Poacher",
    "Assassin",
    "Knight",
    "Elite Knight",
    "Champion Knight",
    "Paladin",
    "Templar Knight",
    "Veteran Commander",
    "Battle Mage",
    "Holy Necromancer",
    "Warlock",
    "Sorcerer",
    "Elemental Mage",
    "Witch",
    "Druid",
    "Ranger",
    "Marksman",
    "Bowmaster",
    "Warrior Priest",
    "Warrior Monk",
    "Fighter",
    "Gladiator",
    "Barbarian",
    "Hero's Squire",
    "Hero's Apprentice",
    "Champion",
    "Dragon Slayer",
    "Famed Gladiator",
    "Legendary Hero",
    "Summoned Hero",
    "Celestial Warrior",
    "Divine Champion",
    "Celestial Paladin",
    "Ancient Titan",
    "Demon Hunter",
    "Elder Mage",
    "Dragon Lord",
    "War God",
    "Immortal Hero",
    "Ascended Champion",
    "Demigod",
    "Behemoth",
    "Godslayer",
    "Angel",
    "ArchAngel",
    "Seraphim",
    "God King",
    "Humanity's Savior",
    "Mightiest Warrior",
    "World's Last Hope",
    "Champion of Light",
    "The Immovable Knight",
    "Defender of the Realm",
    "The Eternal Guardian",
    "The Shield of the People",
    "The Brave One",
    "The Undying Hero",
    "Wielder of the Sacred Blade",
    "The Unyielding Paladin",
    "The Unbreakable",
    "The Titan Slayer",
    "The Grandmaster",
    "Master of the Elements",
    "The Chosen Knight",
    "The Savior of Nations",
    "The Hero of the Ages",
    "The Celestial Champion",
    "The Eternal King",
    "The Legendary Titan",
    "The Invincible",
    "The Great Protector",
    "The Divine Crusader",
    "The Worldbreaker",
    "The Everlasting Flame",
    "The Unstoppable Force",
    "The Arcane Warden",
    "The Dawnbringer",
    "The Last Avenger",
    "The Heroic King",
    "The Undefeated Gladiator",
    "The Divine Knight",
    "The Sword of Fate",
    "The Warlord of Humanity",
    "The Immortal Champion",
    "The Godslayer",
    "The Eternal Champion",
    "The Reborn Hero",
    "The Final Bastion",
    "The Divine Wrath",
    "The Grand Protector",
    "The Sacred Champion",
    "The Last Champion",
    "The Unholy Knight",
    "The Unstoppable Crusader",
    "Hero"
];


const titles = [
  "Player",
  "Aspiring Mage",
  "Novice of the Occult",
  "Chosen One",
  "Shadow Initiate",
  "Acolyte of Shadows",
  "Dark Disciple",
  "Cursed Novice",
  "Demonling",
  "Dark Aspirant",
  "Forsaken Conjurer",
  "Cursed Sorcerer",
  "Dark Mage",
  "Nightcaller",
  "Shadow Caster",
  "Umbral Adept",
  "Dread Evoker",
  "Hexbound Magus",
  "Undead Lich",
  "Bloodbound Warlock",
  "Fallen Champion",
  "Shadow Knight",
  "Dark Warlord",
  "Accursed General",
  "Infernal Conqueror",
  "Hellbound Reaver",
  "Dread Commander",
  "Abyss Tactician",
  "Demon’s Envoy",
  "Infernal Herald",
  "Infernal Executioner",
  "Nightmare Assassin",
  "Abyss Walker",
  "Shadow Marauder",
  "Demonic Vanguard",
  "Fiendish Sentinel",
  "Nightmare Overlord",
  "Terror Sovereign",
  "Archdemon",
  "Undying Monarch",
  "Immortal Lord of Malice",
  "Hell’s General",
  "Sinbound Monarch",
  "Abyss Tyrant",
  "Chaos Tyrant",
  "Dread Lord of Chaos",
  "Dark Realm Conqueror",
  "Sovereign",
  "Archfiend Sovereign",
  "Undying Sovereign",
  "Infernal Lord Regent",
  "Abyssal Emperor",
  "Hell’s Dominion",
  "Demonic Overlord",
  "Netherworld King",
  "Hell’s Regent",
  "Infernal Tyrant",
  "Calamity of the Abyss",
  "Abyssal Destroyer",
  "Demonic God",
  "Dark Deity",
  "Infernal Deity",
  "Voidborne Tyrant",
  "Abyssal Primarch",
  "Chaos Embodiment",
  "Chaos Incarnate",
  "Supreme God of Malice",
  "Demonic Eternal",
  "Lord of Infinite Shadows",
  "Abyssal Paragon",
  "Netherworld Ruler",
  "Demon God of Annihilation",
  "Voidlord Eternal",
  "Abyssal Devourer",
  "Primordial Nightmare",
  "Oblivion Monarch",
  "Infinite Shadow Sovereign",
  "Cosmic Harbinger of Doom",
  "Darkness Beyond Reality",
  "Eternal Abyss Overlord",
  "Chaosborn Titan",
  "Netherworld Paragon",
  "Oblivion Deity",
  "Endless Calamity Incarnate",
  "Voidborne God-King",
  "Darkness Incarnate",
  "Primordial Chaos Deity",
  "The Nameless Shadow",
  "The One Beyond Darkness",
  "Primordial Demon King",
  "Sovereign of the End",
  "Eclipse Overlord",
  "The Abyss Eternal",
  "Dark Sovereign of Oblivion",
  "Shadowborn Deity",
  "The Infernal Creator",
  "Cosmic Lord of Ruin",
  "God of Infinite Dread",
  "Darklord",
  "Evil God",
  "The Eternal",
  "Void Tyrant",
  "Dark One",
  "Demonlord"
];

